pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM',
                    branches: [[name: '']], // Define the branch you want to build
                    userRemoteConfigs: [[url: 'https://github.com/rivkyschon/DevConnect-.git']],
                    extensions: [[$class: 'WildcardSCMHeadFilter']]
                ])
            }
        }
        // Add more stages as needed
    }
}
